### PR TITLE
Affiliations examples update

### PR DESCRIPTION
**Pull request by chris-konrad**
Forgot to change the examples earlier. Now they are more realistic. What bugs me a little is that the 16-digit orcids are super chunky. Is that how its intended in the original template?

### CODE REVIEW

**Comment by moorepants** [comment]
> What bugs me a little is that the 16-digit orcids are super chunky. Is that how its intended in the original template?

I don't know. They just had like xxxx in place of the ID, so they may not have thought it out.

**Comment by chris-konrad** [comment]
Orcid-icon with link would be best I guess. Don't know if thats suitable for the odt/docx template though.

**Comment by moorepants** [comment]
These will all be converted to HTML on Orvium, so they may do that. I think they will generate a new PDF too. So, these templates may not be the exact thing the public sees.

**Comment by moorepants** [comment]
Thus, they may handle the IDs better there.

**Pull request merged**
