### PR TITLE
added highlighs to changeable parts of header and footer

### PR DESCRIPTION
**Pull request by chris-konrad**
#13: Clearly state what should be edited and what not

I highlighted the parts that should be edited in bright yellow and added instructions in the text. Highlights are in the title section and the footer. Is that correct? I was not sure if the ORCHID should remain and the authors should paste their ID behind that or if it should be placed with the actual ID. 

Also, there was a wrong semicolon behind "Author one". I replaced it with a comma.

### CODE REVIEW

**Comment by moorepants** [comment]
Also highlight the author names in the footer, they should edit that.

**Comment by moorepants** [comment]
I see your highlight in the footer of the second page, but not the first.

**Comment by moorepants** [comment]
Oddly editing the test in the footer on the first page doesn't affect the second page and vice versa. Not sure why.

**Comment by moorepants** [comment]
Maybe say: "Please add this information to the header and footer by replacing the highlighted text with your details and remove the yellow highlighting after replacement."

**Comment by chris-konrad** [comment]
> Oddly editing the test in the footer on the first page doesn't affect the second page and vice versa. Not sure why.

It seems that libre office internally creates two different page styles for the first and the second page and also the checkbox "same footer on first page" is ticked, this does not keep track of changes between the page styles. I could not find a workaround, hence let's add: "The footer on the first and second page both have to be edited individually."

> Maybe say: "Please add this information to the header and footer by replacing the highlighted text with your details and remove the yellow highlighting after replacement."

Sounds good.

**Comment by chris-konrad** [comment]
I committed the changes. Should be good now

**Comment by moorepants** [comment]
Thanks. I just reviewed. Merging.

**Pull request merged**
